export const tag = [
    { key: 'FISHING' },
    { key: 'SAILING' },
    { key: 'RESEARCH' },
    { key: 'CARTOGRAPHY' },
    { key: 'REPAIR' },
    { key: 'STORM' },
    { key: 'VOID' },
    { key: 'SLUDGE' },
    { key: 'TROPICAL' },
    { key: 'ELECTRONIC' },
    { key: 'FLESH' },
    { key: 'MIRROR' },
];

export const flOpenPlayer = [
    `**"{0}"** {1} mutters under their breath, lost in thought.`,
    `**"{0}"** {1} exclaims excitedly, eyes wide with enthusiasm.`,
    `**"{0}"** {1} whispers softly, barely audible.`,
    `**"{0}"** {1} shouts angrily, fists clenched.`,
    `**"{0}"** {1} murmurs sleepily, stifling a yawn.`,
    `**"{0}"** {1} laughs heartily, a grin spreading across their face.`,
    `**"{0}"** {1} says sternly, their gaze unwavering.`,
    `**"{0}"** {1} sighs heavily, their shoulders slumping.`,
    `**"{0}"** {1} ponders aloud, tapping their chin thoughtfully.`,
    `**"{0}"** {1} groans in frustration, running a hand through their hair.`,
    `**"{0}"** {1} teases playfully, a mischievous twinkle in their eye.`,
    `**"{0}"** {1} utters coldly, a chill in their voice.`,
    `**"{0}"** {1} remarks cheerfully, giving a thumbs-up.`,
    `**"{0}"** {1} stammers nervously, their cheeks flushing.`,
    `**"{0}"** {1} declares proudly, chin lifted high.`,
    `**"{0}"** {1} mumbles distractedly, fiddling with a pen.`,
    `**"{0}"** {1} shrieks in surprise, jumping back.`,
    `**"{0}"** {1} chortles, their body shaking with laughter.`,
    `**"{0}"** {1} quips sarcastically, rolling their eyes.`,
    `**"{0}"** {1} responds calmly, their voice steady.`,
    `**"{0}"** {1} mutters impatiently, tapping their foot.`,
    `**"{0}"** {1} asserts confidently, hands on hips.`,
    `**"{0}"** {1} hums to themselves, swaying slightly.`,
    `**"{0}"** {1} confesses quietly, looking away.`,
    `**"{0}"** {1} inquires curiously, tilting their head to the side.`,
    `**"{0}"** {1} shivers, their voice quivering with fear.`,
    `**"{0}"** {1} muses dreamily, staring off into the distance.`,
    `**"{0}"** {1} bellows loudly, startling everyone around.`,
    `**"{0}"** {1} snickers, covering their mouth with a hand.`,
    `**"{0}"** {1} replies coolly, arching an eyebrow.`,
].map((fl) => ({ content: fl }));
export const flStormPlayer = [
    `**"{0}"** {1} shouts over the roar of the storm, barely heard above the wind and rain.`,
    `**"{0}"** {1} grimaces as a bolt of lightning strikes nearby, the thunder drowning out their words.`,
    `**"{0}"** {1} clutches their coat tightly, their voice barely carrying over the howling gale.`,
    `**"{0}"** {1} squints through the driving rain, their words snatched away by the storm.`,
    `**"{0}"** {1} struggles to be heard over the crashing waves, their voice lost in the tumult.`,
    `**"{0}"** {1} yells to be heard over the deafening thunder, their words whipped away by the wind.`,
    `**"{0}"** {1} winces as the boat lurches, their voice rising above the creaking timbers.`,
    `**"{0}"** {1} shivers as the cold rain lashes their face, their words barely audible.`,
    `**"{0}"** {1} clings to the railing as the boat pitches, their voice rising and falling with the swell.`,
    `**"{0}"** {1} struggles to keep their footing on the slick deck, their words snatched away by the storm.`,
    `**"{0}"** {1} gasps as a wave crashes over the bow, their voice lost in the roar of the sea.`,
    `**"{0}"** {1} braces against the railing as the boat rolls, their words drowned out by the storm.`,
    `**"{0}"** {1} shouts to be heard over the crashing waves, their voice barely carrying above the din.`,
    `**"{0}"** {1} huddles against the mast, their words muffled by the howling wind.`,
    `**"{0}"** {1} strains to be heard over the deafening thunder, their voice barely audible.`,
    `**"{0}"** {1} grimaces as the boat shudders, their words lost in the creaking of the timbers.`,
    `**"{0}"** {1} clutches their hat as the wind snatches at it, their voice rising above the gale.`,
    `**"{0}"** {1} winces as the rain lashes their face, their words barely carrying over the storm.`,
].map((fl) => ({ content: fl, tag: 'STORM' }));
export const flVoidPlayer = [
    `**"{0}"** {1} whispers, their voice echoing into the endless abyss.`,
    `**"{0}"** {1} murmurs cautiously, eyes scanning the empty expanse.`,
    `**"{0}"** {1} shouts defiantly, their voice swallowed by the void's silence.`,
    `**"{0}"** {1} chuckles nervously, the sound fading into the nothingness.`,
    `**"{0}"** {1} states flatly, their words hanging in the air with no response.`,
    `**"{0}"** {1} sighs, their breath forming a fleeting cloud before vanishing.`,
    `**"{0}"** {1} exclaims eagerly, the vast emptiness offering no reply.`,
    `**"{0}"** {1} utters softly, their voice barely making a ripple in the stillness.`,
    `**"{0}"** {1} growls, frustration building in the endless dark.`,
    `**"{0}"** {1} cackles madly, the sound reverberating through the void.`,
    `**"{0}"** {1} stammers, overwhelmed by the oppressive emptiness.`,
    `**"{0}"** {1} questions hesitantly, the silence stretching infinitely before them.`,
    `**"{0}"** {1} scoffs, the void reflecting nothing of their disdain.`,
    `**"{0}"** {1} gasps, the vast nothingness offering no comfort.`,
    `**"{0}"** {1} hums idly, their tune disappearing into the black void.`,
].map((fl) => ({ content: fl, tag: 'VOID' }));
export const flSludgePlayer = [
    `**"{0}"** {1} grimaces, the stench of decay thick in the air.`,
    `**"{0}"** {1} coughs, the foul sludge clinging to their throat.`,
    `**"{0}"** {1} shudders, the oily water lapping at the boat's hull.`,
    `**"{0}"** {1} gags, the noxious fumes overwhelming their senses.`,
    `**"{0}"** {1} winces, the sludge squelching beneath their boots.`,
    `**"{0}"** {1} groans, the thick water dragging at the boat's keel.`,
    `**"{0}"** {1} mutters, the sludge bubbling ominously around the boat.`,
    `**"{0}"** {1} whispers, the oily film coating their skin.`,
    `**"{0}"** {1} snarls, the sludge seeping into every crevice.`,
    `**"{0}"** {1} chuckles darkly, the stench of rot heavy in the air.`,
    `**"{0}"** {1} sighs, the oily water lapping at the boat's sides.`,
    `**"{0}"** {1} grumbles, the sludge clinging to the boat's hull.`,
    `**"{0}"** {1} hisses, the noxious fumes burning their eyes.`,
    `**"{0}"** {1} growls, the thick water dragging at the boat's keel.`,
    `**"{0}"** {1} murmurs, the sludge squelching beneath their boots.`,
].map((fl) => ({ content: fl, tag: 'SLUDGE' }));
export const flTropicalPlayer = [
    `**"{0}"** {1} grins, the warm sun on their face.`,
    `**"{0}"** {1} laughs, the scent of flowers on the breeze.`,
    `**"{0}"** {1} hums, the crystal waters calming their soul.`,
    `**"{0}"** {1} sighs contentedly, the gentle waves lulling them.`,
    `**"{0}"** {1} chuckles, the vibrant coral beneath the surface.`,
    `**"{0}"** {1} beams, the sun shining brightly overhead.`,
    `**"{0}"** {1} whispers, the warm air wrapping around them.`,
    `**"{0}"** {1} exclaims, the tropical birds calling in the distance.`,
    `**"{0}"** {1} muses, the palm trees swaying gently.`,
    `**"{0}"** {1} murmurs, the scent of salt and flowers mingling.`,
    `**"{0}"** {1} grumbles, the heat of the sun beating down.`,
    `**"{0}"** {1} chuckles, the fish darting playfully below.`,
    `**"{0}"** {1} sighs, the warm breeze ruffling their hair.`,
    `**"{0}"** {1} laughs, the sun casting a golden glow.`,
    `**"{0}"** {1} hums, the crystal waters calming their soul.`,
].map((fl) => ({
    content: fl,
    tag: 'TROPICAL',
}));
export const flElectronicPlayer = [].map((fl) => ({
    content: fl,
    tag: 'ELECTRONIC',
}));
export const flFleshPlayer = [].map((fl) => ({ content: fl, tag: 'FLESH' }));
export const flMirrorPlayer = [].map((fl) => ({ content: fl, tag: 'MIRROR' }));
export const flOpenBoat = [
    'The boat creaks as it drifts, its old wood groaning with every subtle shift of the waves.',
    'A thick fog rolls in, swallowing the bow of the boat and hiding the water ahead.',
    "A splash is heard of something heavy hitting the water, but when you look, there's nothing there",
    'The smell of salt and seaweed hangs in the air, mingling with the scent of damp wood.',
    'A distant, haunting melody floats over the water, growing louder for a moment before fading away',
    'Small fish leap out of the water, their silver scales flashing in the dim light before they disappear back into the depths.',
    'The boat sways gently, lulled by a soft breeze that seems to whisper just out of reach',
    'A shadow moves beneath the surface, circling the boat once before vanishing into the deep',
    'The lantern on deck swings with the motion of the boat, casting flickering shadows that dance across the water.',
    'The sound of a bell rings out from somewhere, though the source is hidden in the fog.',
    'The water around the boat becomes eerily still, as if holding its breath, waiting for something',
    'The sun tries to break through the clouds, casting brief rays of light before being swallowed again by the gray.',
    'A sudden splash sends ripples across the water, but whatever caused it remains unseen.',
].map((fl) => ({ content: fl, subject: 'BOAT' }));
export const flStormBoat = [
    'Thunder rumbles in the distance, a deep, resonant growl that vibrates through the air and the bones of the boat.',
    'The sky above churns with angry clouds, flashes of lightning illuminating the dark waters in brief, blinding bursts.',
    'Waves crash against the sides of the boat, sending sprays of cold saltwater into the air, drenching everything it touches.',
    'The wind howls through the rigging, pulling at the sails like a wild beast determined to tear them free.',
    'Rain falls in sheets, slapping against the deck and mixing with the churning sea in a never-ending torrent.',
    'The boat pitches violently with every swell, groaning under the strain as the sea threatens to swallow it whole.',
    'The sky is a swirl of black and gray, broken only by the occasional bolt of lightning that splits the heavens with a deafening crack.',
    'The air feels thick and oppressive, charged with the electric energy of the storm, as if the very sky is waiting to strike.',
    'A monstrous wave rises ahead, towering over the boat before crashing down with a roar, its force shaking the vessel to its core.',
    'The lantern swings wildly, its light barely cutting through the deluge, casting frantic shadows that flicker and disappear in the rain.',
    'The once distant rumble of thunder is now a constant, echoing boom, like the drums of some ancient, vengeful god.',
    'The boat fights against the relentless wind, its sails flapping desperately, as the storm pushes it further off course.',
    'A jagged streak of lightning illuminates the sea for a moment, revealing the crest of a wave as it curls toward the boat, hungry and unrelenting.',
    'The air tastes of salt and ozone, a bitter tang that clings to your lips as you struggle to breathe against the wind.',
    'The water roils beneath the boat, rising and falling in chaotic waves, as if the sea itself is alive and angry.',
].map((fl) => ({
    content: fl,
    subject: 'BOAT',
    tag: 'STORM',
}));
export const flVoidBoat = [
    'The boat drifts through a sea of darkness, the water black and still as far as the eye can see.',
    'The sky above is a void, empty of stars or moon, leaving the boat adrift in an endless night.',
    'The air is cold and heavy, thick with the weight of the void that surrounds the boat on all sides.',
    'The boat seems to suddenly be pulled sideways, but only for a moment',
    'A shadow moves beneath the surface, circling the boat once before vanishing into the deep',
].map((fl) => ({
    content: fl,
    subject: 'BOAT',
    tag: 'VOID',
}));
export const flSludgeBoat = [
    'The water around the boat is thick and oily, clinging to the hull like a noxious film.',
    'The smell of decay hangs heavy in the air, mingling with the stench of rotting fish and stagnant water.',
    'A strange sludge clings to the sides of the boat, oozing and bubbling as if alive.',
    'There are fears that the boat will be stuck in the thickness of the water, but it continues to move',
    'The water seems to be pulling the boat down, but the boat continues to float',
].map((fl) => ({
    content: fl,
    subject: 'BOAT',
    tag: 'SLUDGE',
}));
export const flTropicalBoat = [
    'The sun beats down from a brilliant blue sky, casting the water in a dazzling array of colors.',
    'The air is warm and heavy with humidity, the scent of salt and flowers mingling on the breeze.',
    'The water is crystal clear, revealing a world of vibrant coral and darting fish beneath the surface.',
    'The boat glides smoothly through the calm waters, the gentle lapping of the waves a soothing rhythm.',
    'The sun is so bright it is difficult to see',
].map((fl) => ({
    content: fl,
    subject: 'BOAT',
    tag: 'TROPICAL',
}));
export const flElectronicBoat = [
    'The water around the boat is littered with strange devices, their lights blinking and screens flickering.',
    'The air is filled with the hum of electricity, a constant buzz that seems to vibrate through the boat.',
    'The boat seems to be pulled in a certain direction by the devices, but the crew is able to resist',
    'The devices in the water seem to be communicating with each other, but the language is unknown',
].map((fl) => ({
    content: fl,
    subject: 'BOAT',
    tag: 'ELECTRONIC',
}));
export const flFleshBoat = [
    'The water around the boat is tinged with red, the smell of iron and decay heavy in the air.',
    'The fish that swim beneath the surface are not fish at all, but writhing masses of flesh and muscle.',
    'The boat seems to be moving through the flesh of the water, but the crew is able to continue',
    'The flesh in the water seems to be reaching out for the boat, but the boat continues to move',
].map((fl) => ({
    content: fl,
    subject: 'BOAT',
    tag: 'FLESH',
}));
export const flMirrorBoat = [
    'The water around the boat is perfectly still, reflecting the sky above like a mirror.',
    'The crew can see their own reflections in the water, but they seem to be moving independently',
    'The boat seems to be moving in a different direction in the reflection, but the crew is able to continue',
    'The reflection of the boat seems to be getting closer, but the boat continues to move',
].map((fl) => ({
    content: fl,
    subject: 'BOAT',
    tag: 'MIRROR',
}));

export const flavor = () => {
    return flOpenPlayer.concat(
        flStormPlayer,
        flVoidPlayer,
        flSludgePlayer,
        flTropicalPlayer,
        flElectronicPlayer,
        flFleshPlayer,
        flMirrorPlayer,
        flOpenBoat,
        flStormBoat,
        flVoidBoat,
        flSludgeBoat,
        flTropicalBoat,
        flElectronicBoat,
        flFleshBoat,
        flMirrorBoat,
    );
};

export const skill = [
    { key: 'FISH', name: 'Fish' },
    { key: 'SAIL', name: 'Sailing' },
    { key: 'RESEARCH', name: 'Research' },
    { key: 'CARTOGRAPHY', name: 'Cartography' },
    { key: 'REPAIR', name: 'Repair' },
];

export const biome = [
    {
        key: 'OPEN_OCEAN',
        name: 'Open Ocean',
        info: 'The world is now ocean as far as the eye can see.',
    },
    {
        key: 'STORM',
        name: 'Storm',
        info: 'The air in this region is thick with the smell of ozone, clouds are converging rapidly and the rain falls heavily.',
    },
    {
        key: 'VOID',
        name: 'Void',
        info: 'No matter the time of day this area is always dark, the air is cold and especially bottomless. Its more difficult to smile here.',
    },
    {
        key: 'SLUDGE',
        name: 'Sludge',
        info: 'The water in this region is thick and oily, the smell is overpowering and you wonder how the boat is capable of moving through this liquid.',
    },
    {
        key: 'TROPICAL',
        name: 'Tropical',
        info: 'The water is warm and clear, the sun is shining and the fish are plentiful. This is the best place to be on The Boat, although the sun does seem to be burning brighter and brighter...',
    },
    {
        key: 'ELECTRONIC',
        name: 'Electronic',
        info: 'This area has an unusual number of devices found floating in the water. Every now and then you come across poles jutting out filled with cables and circuitry.',
    },
    {
        key: 'FLESH',
        name: 'Flesh',
        info: 'The water in this region seems to have a tint of red, the smell is of iron and the fish are... different. The fish here are not fish, they are flesh, they are meat, they are muscle.',
    },
    {
        key: 'MIRROR',
        name: 'Mirror',
        info: 'The water in this region is perfectly still, the sky is reflected perfectly in the water. Staring into the water takes you further and further from reality into non euclidean insanity.',
    },
];

export const biomeCoords = [
    { biomeKey: 'TROPICAL', topLeft: [-8, -7], bottomRight: [-3, -2] },
    { biomeKey: 'VOID', topLeft: [-1, -2], bottomRight: [2, 1] },
    { biomeKey: 'STORM', topLeft: [1, -9], bottomRight: [4, -6] },
    { biomeKey: 'SLUDGE', topLeft: [4, -5], bottomRight: [9, -1] },
    { biomeKey: 'FLESH', topLeft: [-8, 3], bottomRight: [-5, 6] },
    { biomeKey: 'MIRROR', topLeft: [-1, 4], bottomRight: [3, 8] },
    { biomeKey: 'ELECTRONIC', topLeft: [6, 1], bottomRight: [8, 5] },
];

export const item = [
    {
        key: 'GAS_TROUT',
        name: 'Gas trout',
        description: 'This fish seems to have gasoline in place of blood',
        info: 'It seems this fish can be found anywhere in the ocean',
    },
    {
        key: 'TROUT',
        name: 'Trout',
        description: 'Ok this one has actual blood',
        info: 'Trout can reach the ripe old age of 20 years',
    },
    {
        key: 'TRUMPETFISH',
        name: 'Trumpetfish',
        description: 'A strange long fish with a rectangular body',
        info: 'Not much is known about trumpetfish reproduction, they probably dance',
    },
    {
        key: 'BLUEBANDED_GOBY',
        name: 'Bluebanded Goby',
        description: 'An orange with striking blue stripes',
        info: 'The bluebanded goby is originally from the Indo-Pacific region',
    },
    {
        key: 'SALMON',
        name: 'Salmon',
        description: 'A silver fish which is a popular food source',
        info: 'The salmon swims upstream to spawn, there is no upstream anymore',
    },
    {
        key: 'ELECTRIC_EEL',
        name: 'Electric Eel',
        description:
            'A snakelike fish that can produce electricity to stun prey',
        info: 'The study of the electric eel has led to the invention of the battery, probably',
    },
    {
        key: 'BLUEHEADED_WRASSE',
        name: 'Blueheaded Wrasse',
        description: 'A multicolored fish with a blue head',
        info: 'This one knows how to party',
    },
    {
        key: 'SEADRAGON',
        name: 'Seadragon',
        description: 'A small fish with leaf-like appendages for camouflage',
        info: 'The seadragon is a close relative of the seahorse',
    },
    {
        key: 'SNIPE_EEL',
        name: 'Snipe Eel',
        description:
            'A long, thin fish with a pointed snout and no pelvic fins',
        info: 'This fish would be mostly tail if it weren’t for the head',
    },
    {
        key: 'FLASHLIGHT_FISH',
        name: 'Flashlight Fish',
        description: 'A fish with bioluminescent organs under its eyes',
        info: 'Keeping one of these in a jar could be useful',
    },
    {
        key: 'ANGLERFISH',
        name: 'Anglerfish',
        description: 'A fish with a bioluminescent lure on its head',
        info: 'Your studies find these fish are growing exponentially...',
    },
    {
        key: 'JOHN_DORY',
        name: 'John Dory',
        description: 'A flat, round fish with a black spot on its side',
        info: 'It is rumoured that the John Dory is the fish that swallowed Jonah',
    },
    {
        key: 'GRUNION',
        name: 'Grunion',
        description: 'A small fish that spawns on beaches at night',
        info: 'The grunion is a popular fish in California, you suddenly miss california deeply',
    },
    {
        key: 'LONG_SNOUTED_SEAHORSE',
        name: 'Long snouted seahorse',
        description:
            'A seahorse with a long snout, it looks like an actual horse ',
        info: 'The long snouted seahorse is a close relative of the seadragon',
    },
    {
        key: 'RED_SNAPPER',
        name: 'Red Snapper',
        description: 'A red fish that is popular in cooking',
        info: 'The red snapper is a popular fish in the Gulf of Mexico',
    },
    {
        key: 'DOLPHINFISH',
        name: 'Dolphinfish',
        description: 'A fish with a long dorsal fin and a blunt head',
        info: 'The dolphinfish is not a dolphin, it is a fish, which is different apparently',
    },
    {
        key: 'SAWFISH',
        name: 'Sawfish',
        description: 'A fish with a long, flat snout with teeth on the sides',
        info: 'THE SAWFISH IS NOT A SAW, DO NOT USE IT AS A SAW',
    },
    {
        key: 'QUEEN_ANGELFISH',
        name: 'Queen Angelfish',
        description: 'A colorful fish with a blue ring on its head',
        info: 'This fish whispers secrets when you aren’t looking',
    },
    {
        key: 'DREAMFISH',
        name: 'Dreamfish',
        description:
            'A fish that seems to be made of dreams, but is actually made out of fish',
        info: 'The dreamfish is a rare fish that is said to bring good luck',
    },
    {
        key: 'SARDINE',
        name: 'Sardine',
        description: 'A small fish that is often found in large schools',
        info: 'The sardine is a popular fish in the Mediterranean',
    },
    {
        key: 'OARFISH',
        name: 'Oarfish',
        description: 'A long, thin fish that looks like an oar',
        info: 'The oarfish is a deep sea fish that is rarely seen alive',
    },
    {
        key: 'PYGMY_SEAHORSE',
        name: 'Pygmy Seahorse',
        description: 'A tiny seahorse with a body that looks like coral',
        info: 'The pygmy seahorse is a master of disguise',
    },
    {
        key: 'MEXICAN_LOOKDOWN',
        name: 'Mexican Lookdown',
        description: 'A fish with a flat, silvery body and a downward mouth',
        info: 'THE MEXICAN LOOKDOWN IS NOT JUDGING YOU, IT IS JUST LOOKING DOWN',
    },
    {
        key: 'GUINEAFOWL_PUFFER',
        name: 'Guineafowl Puffer',
        description: 'A fish with black spots on its body',
        info: 'The guineafowl puffer is more dangerous than it looks',
    },
    {
        key: 'BONITO',
        name: 'Bonito',
        description: 'A fish that is related to the tuna',
        info: 'The bonito is the fastest fish in the ocean, except for the fish that are faster',
    },
    {
        key: 'TRUMPET',
        name: 'Trumpet',
        description:
            'A classic brass instrument now covered in barnacles and rust',
        info: 'When played it sounds like the ocean, but a different ocean than this one',
    },
    {
        key: 'LIGHTNING_BOTTLE',
        name: 'Lightning in a bottle',
        description:
            'A bottle filled with what seems to be lightning bouncing around the inside',
        info: 'The bottle seems to go through phases of activity apparently influenced by the weather',
    },
    {
        key: 'GOLD_COINS',
        name: 'Gold coins',
        description: 'A small pile of gold coins in a suspiciously dry pouch',
        info: 'Each coin is stamped with the face of a different king, none of whom you recognize, some lack common human features',
    },
    {
        key: 'SPYGLASS',
        name: 'Spyglass',
        description: 'A telescope with strange symbols etched into the side',
        info: 'Sometimes when you look through the spyglass you see land that isn’t there',
    },
    {
        key: 'PLAYING_CARDS',
        name: 'Deck of playing cards',
        description:
            'A deck of cards with with suits you are not familiar with such as soul',
        info: 'The cards seem to shuffle themselves when you aren’t looking, Does the configuration of the cards mean something?',
    },
    {
        key: 'DARKNESS_JAR',
        name: 'Darkness in a jar',
        description: 'A jar filled with darkness that seems to absorb light',
        info: 'When you open the jar the darkness spills out and fills the room, it is time consuming to scoop back up',
    },
    {
        key: 'CERULEAN_JADE',
        name: 'Cerulean Jade',
        description: 'A small piece of jade that is a deep blue color',
        info: 'The cerulean jade is said to bring good luck to sailors',
    },
    {
        key: 'IPOD',
        name: 'iPod',
        description: 'A small device that plays music from a different time',
        info: 'Most of these songs are undisputed classics, some are 20 minutes of screaming and incoherent uttering',
    },
    {
        key: 'SPEAKERS',
        name: 'Speakers',
        description:
            'A pair of speakers that can play audio at a high volume, useful with the iPod',
        info: 'They sometimes play music on their own, it is not always music',
    },
    {
        key: 'SKIN_INTERFACE',
        name: 'Skin interface',
        description:
            'A pill shaped object with tendrils coming off of it. These tendrils seem to integrate with any living flesh they come into contact with.',
        info: 'The longer this object is embedded with a living creature the more difficult it is to remove',
    },
    {
        key: 'SMOOTH_STONE',
        name: 'Oddly smooth stone',
        description: 'A stone that is perfectly smooth on all sides',
        info: 'Despite its complete smoothness the stone always stops at the same point when rolled',
    },
    {
        key: 'BONE_DAGGER',
        name: 'Bone dagger',
        description: 'A dagger made from seems to be whale bone',
        info: 'The dagger is sharper than it looks being capable of even cutting the metal on The Boat',
    },
    {
        key: 'DIAMOND_ENCRUSTED_DIAMOND',
        name: 'Diamond encrusted diamond',
        description:
            'A diamond with smaller diamonds purposefully embedded in it',
        info: 'You cannot confirm it but you suspect the placement of these diamonds ',
    },
    {
        key: 'VIRTUAL_REALITY_TUBE',
        name: 'Virtual reality tube',
        description:
            'A tube that goes around the users head and projects a lifelike virtual reality',
        info: 'The environment the user is put into seems dependant on their real world surroundings',
    },
    {
        key: 'STORY_SCALE',
        name: 'Story scale',
        description:
            'A piece of porcelain vibrates when a story is spoken near it',
        info: 'The story scale seems to be able to tell the difference between a true story and a lie',
    },
    {
        key: 'OBSIDIAN_SHARD',
        name: 'Obsidian shard',
        description: 'A shard of obsidian darker than the night',
        info: 'The obsidian shard seems to absorb light, it is difficult to look at for too long',
    },
    {
        key: 'SITCOM_VCR',
        name: '90s sitcom VCR',
        description: 'A VCR that plays a different show every time it is used',
        info: 'For one minute in one viewing, you and everyone else on The Boat appear in the show. Before one of you can say a line, the show ends',
    },
    {
        key: 'GLOWING_SCARAB',
        name: 'Glowing scarab',
        description: 'A beetle that glows with a soft light',
        info: 'The glowing scarab seems to be able to predict the weather, it is always wrong',
    },
    {
        key: 'SLUDGE_BLOOM',
        name: 'Sludge bloom',
        description: 'A beautiful flower that secretes a foul brown liquid',
        info: 'You decide not to taste the liquid...',
    },
    {
        key: 'AMBERGRIS',
        name: 'Ambergris',
        description:
            'A waxy substance that is produced in the intestines of sperm whales',
        info: 'One of you decide to taste the ambergris, they awaken three days later with a slightly different cadence to their speech',
    },
    {
        key: 'MEMORY_SHARD',
        name: 'Shard of memory',
        description:
            'A shard of glass that makes you remember things that did not happen',
        info: 'Prolonged use of the memory shard can cause real memories to be replaced',
    },
    {
        key: 'INWARD_SPECTACLES',
        name: 'Inward Spectacles',
        description: 'A pair of glasses that cause the wearer to hallucinate',
        info: 'The hallucinations seem to have a consistent pattern between users',
    },
    {
        key: 'MIRRORED_PUZZLE_BOX',
        name: 'Mirrored puzzle box',
        description:
            'A reflective puzzle box that you have not been able to solve yet',
        info: 'A slide and a click, you have come one step closer to solving the puzzle',
    },
    {
        key: 'BOOT',
        name: 'Boot',
        description: 'This is a boot',
        info: 'Size 10 UK',
    },
    {
        key: 'STICK',
        name: 'Stick',
        description: 'This is a stick',
        info: 'Size 10 US',
    },
    {
        key: 'BOTTLE_NOTE',
        name: 'Note in a bottle',
        description: 'A corked bottle with a note slid inside',
        info: 'The note is written in a language you do not recognize, it is signed with a symbol of an Octopus',
    },
    {
        key: 'WRENCH',
        name: 'Wrench',
        description: 'This wrench will help to repair the boat',
        info: 'Its a wrench',
    },
];

export const use = [
    {
        key: 'INC_XP_PLAYER_RANDOM',
        name: 'Increases a players XP in a random skill',
    },
    { key: 'INC_XP_PLAYER_ALL', name: 'Increases a players XP in all skills' },
    {
        key: 'INC_XP_BOAT_RANDOM',
        name: 'Increases the boats XP in a random skill',
    },
    { key: 'INC_XP_BOAT_ALL', name: 'Increases the boats XP in all skills' },
    { key: 'REPAIR_ONE', name: 'Repairs one random defect on the boat' },
    { key: 'REPAIR_ALL', name: 'Repairs all defects on the boat' },
    { key: 'INC_SPEED', name: 'Applies the Sail Time buff' },
];

export const itemUse = [
    {
        itemKey: 'WRENCH',
        useKey: 'REPAIR_ALL',
        variable: 1,
    },
    {
        itemKey: 'WRENCH',
        useKey: 'INC_XP_BOAT_ALL',
        variable: 1,
    },
];

export const itemTransformation = [
    { original: 'PYGMY_SEAHORSE', transformation: 'SEADRAGON' },
    { original: 'SEADRAGON', transformation: 'PYGMY_SEAHORSE' },
    { original: 'TRUMPET', transformation: 'IPOD' },
    { original: 'SITCOM_VCR', transformation: 'SKIN_INTERFACE' },
    { original: 'FLASHLIGHT_FISH', transformation: 'GLOWING_SCARAB' },
    { original: 'GOLD_COINS', transformation: 'DIAMOND_ENCRUSTED_DIAMOND' },
    { original: 'BOTTLE_NOTE', transformation: 'MIRRORED_PUZZLE_BOX' },
];

export const loot = [
    { id: 1, key: 'FISH', biome: null },
    { id: 2, key: 'FISH', biome: 'STORM' },
    { id: 3, key: 'FISH', biome: 'VOID' },
    { id: 4, key: 'FISH', biome: 'SLUDGE' },
    { id: 5, key: 'FISH', biome: 'TROPICAL' },
    { id: 6, key: 'FISH', biome: 'ELECTRONIC' },
    { id: 7, key: 'FISH', biome: 'FLESH' },
    { id: 8, key: 'FISH', biome: 'MIRROR' },
    { id: 9, key: 'TREASURE', biome: null },
    { id: 10, key: 'TREASURE', biome: 'VOID' },
    { id: 11, key: 'TREASURE', biome: 'STORM' },
    { id: 12, key: 'TREASURE', biome: 'SLUDGE' },
    { id: 13, key: 'TREASURE', biome: 'TROPICAL' },
    { id: 14, key: 'TREASURE', biome: 'ELECTRONIC' },
    { id: 15, key: 'TREASURE', biome: 'FLESH' },
    { id: 16, key: 'TREASURE', biome: 'MIRROR' },
];

export const lootItem = [
    { lootId: 1, itemKey: 'GAS_TROUT', rarity: 'COMMON' },
    { lootId: 1, itemKey: 'TROUT', rarity: 'COMMON' },
    { lootId: 1, itemKey: 'TRUMPETFISH', rarity: 'COMMON' },
    { lootId: 1, itemKey: 'BLUEBANDED_GOBY', rarity: 'COMMON' },
    { lootId: 1, itemKey: 'SALMON', rarity: 'COMMON' },
    { lootId: 1, itemKey: 'BOOT', rarity: 'COMMON' },
    { lootId: 1, itemKey: 'STICK', rarity: 'COMMON' },
    { lootId: 1, itemKey: 'BOTTLE_NOTE', rarity: 'COMMON' },
    { lootId: 9, itemKey: 'TRUMPET', rarity: 'COMMON' },
    { lootId: 9, itemKey: 'GOLD_COINS', rarity: 'COMMON' },
    { lootId: 9, itemKey: 'SPYGLASS', rarity: 'COMMON' },
    { lootId: 9, itemKey: 'PLAYING_CARDS', rarity: 'COMMON' },
    { lootId: 9, itemKey: 'BOOT', rarity: 'COMMON' },
    { lootId: 9, itemKey: 'STICK', rarity: 'COMMON' },
    { lootId: 9, itemKey: 'BOTTLE_NOTE', rarity: 'COMMON' },
    { lootId: 2, itemKey: 'ELECTRIC_EEL', rarity: 'COMMON' },
    { lootId: 2, itemKey: 'BLUEHEADED_WRASSE', rarity: 'COMMON' },
    { lootId: 2, itemKey: 'SEADRAGON', rarity: 'COMMON' },
    { lootId: 11, itemKey: 'LIGHTNING_BOTTLE', rarity: 'COMMON' },
    { lootId: 11, itemKey: 'CERULEAN_JADE', rarity: 'COMMON' },
    { lootId: 3, itemKey: 'SNIPE_EEL', rarity: 'COMMON' },
    { lootId: 3, itemKey: 'FLASHLIGHT_FISH', rarity: 'COMMON' },
    { lootId: 3, itemKey: 'SNIPE_EEL', rarity: 'COMMON' },
    { lootId: 10, itemKey: 'DARKNESS_JAR', rarity: 'COMMON' },
    { lootId: 10, itemKey: 'OBSIDIAN_SHARD', rarity: 'COMMON' },
    { lootId: 10, itemKey: 'SITCOM_VCR', rarity: 'COMMON' },
    { lootId: 4, itemKey: 'JOHN_DORY', rarity: 'COMMON' },
    { lootId: 4, itemKey: 'GRUNION', rarity: 'COMMON' },
    { lootId: 4, itemKey: 'TRUMPETFISH', rarity: 'COMMON' },
    { lootId: 12, itemKey: 'GLOWING_SCARAB', rarity: 'COMMON' },
    { lootId: 12, itemKey: 'SLUDGE_BLOOM', rarity: 'COMMON' },
    { lootId: 12, itemKey: 'AMBERGRIS', rarity: 'COMMON' },
    { lootId: 5, itemKey: 'LONG_SNOUTED_SEAHORSE', rarity: 'COMMON' },
    { lootId: 5, itemKey: 'RED_SNAPPER', rarity: 'COMMON' },
    { lootId: 5, itemKey: 'DOLPHINFISH', rarity: 'COMMON' },
    { lootId: 13, itemKey: 'CERULEAN_JADE', rarity: 'COMMON' },
    { lootId: 13, itemKey: 'DIAMOND_ENCRUSTED_DIAMOND', rarity: 'COMMON' },
    { lootId: 13, itemKey: 'STORY_SCALE', rarity: 'COMMON' },
    { lootId: 6, itemKey: 'SAWFISH', rarity: 'COMMON' },
    { lootId: 6, itemKey: 'QUEEN_ANGELFISH', rarity: 'COMMON' },
    { lootId: 6, itemKey: 'DREAMFISH', rarity: 'COMMON' },
    { lootId: 14, itemKey: 'IPOD', rarity: 'COMMON' },
    { lootId: 14, itemKey: 'SPEAKERS', rarity: 'COMMON' },
    { lootId: 14, itemKey: 'VIRTUAL_REALITY_TUBE', rarity: 'COMMON' },
    { lootId: 7, itemKey: 'SARDINE', rarity: 'COMMON' },
    { lootId: 7, itemKey: 'OARFISH', rarity: 'COMMON' },
    { lootId: 7, itemKey: 'PYGMY_SEAHORSE', rarity: 'COMMON' },
    { lootId: 15, itemKey: 'SKIN_INTERFACE', rarity: 'COMMON' },
    { lootId: 15, itemKey: 'SMOOTH_STONE', rarity: 'COMMON' },
    { lootId: 15, itemKey: 'BONE_DAGGER', rarity: 'COMMON' },
    { lootId: 8, itemKey: 'MEXICAN_LOOKDOWN', rarity: 'COMMON' },
    { lootId: 8, itemKey: 'GUINEAFOWL_PUFFER', rarity: 'COMMON' },
    { lootId: 8, itemKey: 'BONITO', rarity: 'COMMON' },
    { lootId: 16, itemKey: 'MEMORY_SHARD', rarity: 'COMMON' },
    { lootId: 16, itemKey: 'INWARD_SPECTACLES', rarity: 'COMMON' },
];

export const activities = [
    { key: 'FISH', name: 'Fish', allowDuringSail: '0' },
    { key: 'CARTOGRAPHY', name: 'Cartography', allowDuringSail: '0' },
    { key: 'REPAIR', name: 'Repair', allowDuringSail: '0' },
    { key: 'RESEARCH', name: 'Research', allowDuringSail: '0' },
    { key: 'NORTH_SAILING', name: 'North Sailing', allowDuringSail: '1' },
    { key: 'SOUTH_SAILING', name: 'South Sailing', allowDuringSail: '1' },
    { key: 'WEST_SAILING', name: 'West Sailing', allowDuringSail: '1' },
    { key: 'EAST_SAILING', name: 'East Sailing', allowDuringSail: '1' },
];

export const effect = [
    {
        id: 1,
        key: 'FISH_QUALITY',
        name: 'Fish Quality Improved',
        description: 'Fish quality improved',
        type: 'BUFF',
        rarity: 'COMMON',
    },
    {
        id: 2,
        key: 'FISH_QUALITY',
        name: 'Fish Quality Impaired',
        description: 'Fish quality impaired',
        type: 'DEBUFF',
        rarity: 'COMMON',
    },
    {
        id: 3,
        key: 'TREASURE_QUALITY',
        name: 'Treasure Quality Improved',
        description: 'Treasure quality improved',
        type: 'BUFF',
        rarity: 'COMMON',
    },
    {
        id: 4,
        key: 'TREASURE_QUALITY',
        name: 'Treasure Quality Impaired',
        description: 'Treasure quality impaired',
        type: 'DEBUFF',
        rarity: 'COMMON',
    },
    {
        id: 5,
        key: 'TRANSFORMATION_QUALITY',
        name: 'Transformation Quality Improved',
        description: 'Transformation quality improved',
        type: 'BUFF',
        rarity: 'COMMON',
    },
    {
        id: 6,
        key: 'TRANSFORMATION_QUALITY',
        name: 'Transformation Quality Impaired',
        description: 'Transformation quality impaired',
        type: 'DEBUFF',
        rarity: 'COMMON',
    },
    {
        id: 7,
        key: 'FISH_TIME',
        name: 'Fish Time Quicker',
        description: 'Fish time quicker',
        type: 'BUFF',
        rarity: 'COMMON',
    },
    {
        id: 8,
        key: 'FISH_TIME',
        name: 'Fish Time Slower',
        description: 'Fish time slower',
        type: 'DEBUFF',
        rarity: 'COMMON',
    },
    {
        id: 9,
        key: 'CARTOGRAPHY_TIME',
        name: 'Cartography Time Quicker',
        description: 'Cartography time quicker',
        type: 'BUFF',
        rarity: 'COMMON',
    },
    {
        id: 10,
        key: 'CARTOGRAPHY_TIME',
        name: 'Cartography Time Slower',
        description: 'Cartography time slower',
        type: 'DEBUFF',
        rarity: 'COMMON',
    },
    {
        id: 11,
        key: 'REPAIR_TIME',
        name: 'Repair Time Quicker',
        description: 'Repair time quicker',
        type: 'BUFF',
        rarity: 'COMMON',
    },
    {
        id: 12,
        key: 'REPAIR_TIME',
        name: 'Repair Time Slower',
        description: 'Repair time slower',
        type: 'DEBUFF',
        rarity: 'COMMON',
    },
    {
        id: 13,
        key: 'RESEARCH_TIME',
        name: 'Research Time Quicker',
        description: 'Research time quicker',
        type: 'BUFF',
        rarity: 'COMMON',
    },
    {
        id: 14,
        key: 'RESEARCH_TIME',
        name: 'Research Time Slower',
        description: 'Research time slower',
        type: 'DEBUFF',
        rarity: 'COMMON',
    },
    {
        id: 15,
        key: 'SAIL_TIME',
        name: 'Sail Time Quicker',
        description: 'Sail time quicker',
        type: 'BUFF',
        rarity: 'COMMON',
    },
    {
        id: 16,
        key: 'SAIL_TIME',
        name: 'Sail Time Slower',
        description: 'Sail time slower',
        type: 'DEBUFF',
        rarity: 'COMMON',
    },
    {
        id: 17,
        key: 'FISH_XP',
        name: 'More XP for Fishing',
        description: 'More XP for fishing',
        type: 'BUFF',
        rarity: 'COMMON',
    },
    {
        id: 18,
        key: 'FISH_XP',
        name: 'Less XP for Fishing',
        description: 'Less XP for fishing',
        type: 'DEBUFF',
        rarity: 'COMMON',
    },
    {
        id: 19,
        key: 'CARTOGRAPHY_XP',
        name: 'More XP for Cartography',
        description: 'More XP for cartography',
        type: 'BUFF',
        rarity: 'COMMON',
    },
    {
        id: 20,
        key: 'CARTOGRAPHY_XP',
        name: 'Less XP for Cartography',
        description: 'Less XP for cartography',
        type: 'DEBUFF',
        rarity: 'COMMON',
    },
    {
        id: 21,
        key: 'REPAIR_XP',
        name: 'More XP for Repairing',
        description: 'More XP for repairing',
        type: 'BUFF',
        rarity: 'COMMON',
    },
    {
        id: 22,
        key: 'REPAIR_XP',
        name: 'Less XP for Repairing',
        description: 'Less XP for repairing',
        type: 'DEBUFF',
        rarity: 'COMMON',
    },
    {
        id: 23,
        key: 'RESEARCH_XP',
        name: 'More XP for Researching',
        description: 'More XP for researching',
        type: 'BUFF',
        rarity: 'COMMON',
    },
    {
        id: 24,
        key: 'RESEARCH_XP',
        name: 'Less XP for Researching',
        description: 'Less XP for researching',
        type: 'DEBUFF',
        rarity: 'COMMON',
    },
    {
        id: 25,
        key: 'SAIL_XP',
        name: 'More XP for Sailing',
        description: 'More XP for sailing',
        type: 'BUFF',
        rarity: 'COMMON',
    },
    {
        id: 26,
        key: 'SAIL_XP',
        name: 'Less XP for Sailing',
        description: 'Less XP for sailing',
        type: 'DEBUFF',
        rarity: 'COMMON',
    },
];
